import {readFileSync,writeFileSync} from 'node:fs';
const dir='experiments/protected-landing-v1/full-integration';
const verification=JSON.parse(readFileSync(`${dir}/verification.json`,'utf8'));
if(verification.partial||verification.checked!==4)throw Error('Four verified outcomes required');
const current=JSON.parse(readFileSync(`${dir}/results.json`,'utf8')).rows;
const previous=JSON.parse(readFileSync('experiments/extraction-efficiency-v1/full-integration/results.json','utf8')).rows;
const count=(s:any)=>s.alg?.split(/\s+/).filter(Boolean).length??0;
const early=(r:any)=>r.steps.filter((s:any)=>['daisy','cross'].includes(s.decision?.goal)).reduce((n:number,s:any)=>n+count(s),0);
const rows=current.map((r:any)=>{const b=previous.find((b:any)=>b.id===r.id);if(!b||JSON.stringify(b.before)!==JSON.stringify(r.before))throw Error('Unpaired start');return {id:r.id,before:{status:b.status,turns:b.turns,crossTurns:early(b)},after:{status:r.status,turns:r.turns,crossTurns:early(r)},turnDelta:r.status==='solved'&&b.status==='solved'?r.turns-b.turns:null};});
writeFileSync(`${dir}/comparison.json`,JSON.stringify({note:'Paired development starts with saved baseline; later decisions are stochastic. Not held-out reliability.',rows},null,2));console.log(rows);
