import {readRecord} from './read-record';
import {readFileSync,writeFileSync} from 'node:fs';
import {Database} from 'bun:sqlite';
const dir='experiments/full-pll-v1/final100';
const data=await readRecord(`${dir}/results.json`);
const partial=process.argv.includes('--partial');
const verification=JSON.parse(readFileSync(`${dir}/${partial?'partial-verification':'verification'}.json`,'utf8'));
const rows=verification.rows;
if(!partial&&(verification.partial||verification.checked!==100))throw Error('100 verified outcomes required');
const count=(status:string)=>rows.filter((r:any)=>r.status===status).length;
const solved=rows.filter((r:any)=>r.status==='solved');
const turns=solved.map((r:any)=>r.turns).sort((a:number,b:number)=>a-b);
const times=solved.map((r:any)=>r.elapsedMs/1000).sort((a:number,b:number)=>a-b);
const median=(a:number[])=>!a.length?null:a.length%2?a[Math.floor(a.length/2)]:(a[a.length/2-1]+a[a.length/2])/2;
const db=new Database('.data/lab.sqlite',{readonly:true});
const commitment=db.query('SELECT status,COUNT(*) attempts,SUM(amount) dollars FROM ledger GROUP BY status').all();db.close();
const summary={partial,planned:100,verified:rows.length,started:data.rows.length,solved:solved.length,capped:count('capped'),abstained:count('abstained'),transportUnresolved:count('transport-unresolved'),errors:count('error'),budgetStopped:count('budget-stopped'),notStarted:100-data.rows.length,achieved:!partial&&rows.length===100&&solved.length>=95,successfulTurns:{values:turns,min:turns[0]??null,median:median(turns),max:turns.at(-1)??null},successfulSeconds:{min:times[0]??null,median:median(times),max:times.at(-1)??null},usage:data.usage,projectCommitment:verification.projectCommitment,ledger:commitment,nonSuccesses:rows.filter((r:any)=>r.status!=='solved')};
writeFileSync(`${dir}/${partial?'partial-report':'report'}.json`,JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));
