import { useState } from 'react';
import { Cube } from './Cube';
import { names, colors, pieces } from '../lib/cube';
import { netStickers } from '../lib/cube-encoding';
import type { CubeData } from '../lib/types';
const palette: Record<string,string> = {white:'#f5f5ef',yellow:'#f4d542',green:'#57aa70',blue:'#5689d6',red:'#e06962',orange:'#f0a04b'};
const faceNames: Record<string,string> = {U:'Up',D:'Down',F:'Front',B:'Back',R:'Right',L:'Left'};
function Dots({home}: {home:string}) { return <span className="encoding-dots">{[...home].map(face => <i key={face} style={{background:palette[colors[face]]}} title={colors[face]}/>)}</span>; }
export function CubeEncoding({state,previewSetup,observation}: {state:CubeData;previewSetup:string;observation:any}) {
  const [flat,setFlat] = useState(true);
  const [selected,setSelected] = useState('UF');
  const decoded = pieces(state), net = netStickers(state);
  const piece = decoded.find(p => p.position === selected)!;
  const orbit = piece.kind === 'edge' ? 'EDGES' : 'CORNERS';
  const slots = names[orbit], index = slots.indexOf(selected), id = state[orbit].pieces[index], orientation = state[orbit].orientation[index];
  const petals = decoded.filter(p=>p.kind==='edge'&&p.stickers.yellow==='U');
  const uncollected = decoded.filter(p=>p.kind==='edge'&&p.piece.includes('D')&&p.stickers.yellow!=='U'&&!p.solved);
  return <section className="encoding" aria-label="From cube stickers to JEV observations">
    <header className="encoding-heading"><span>START HERE</span><h2>How a cube becomes an observation</h2><p>This is the cube immediately before the selected action. Click a sticker or an array cell to follow one piece through the representation.</p></header>
    <div className="encoding-top">
      <section className="encoding-visual"><h3>1 · The physical stickers</h3>
        <div className="encoding-switch"><button aria-pressed={!flat} onClick={()=>setFlat(false)}>Fold into 3D</button><button aria-pressed={flat} onClick={()=>setFlat(true)}>Unfold all six faces</button></div>
        {flat ? <div className="encoding-net">{Object.entries(net).map(([face,stickers])=><div className={`encoding-face face-${face}`} key={face}><small>{face} · {faceNames[face]}</small><div>{stickers.map(({position,color})=><button key={position} disabled={position.length===1} aria-pressed={position===selected} aria-label={`${face} sticker at ${position}: ${color}`} title={`${position}: ${color} on ${face}`} onClick={()=>setSelected(position)} className={position===selected?'selected':''} style={{background:palette[color]}}>{position.length===1?face:position}</button>)}</div></div>)}</div> : <div className="encoding-3d"><Cube scramble={previewSetup} alg="" speed={1} instant hideControls/></div>}
        <p className="wire-caption">In the unfolded view, sticker labels name their current slots. A highlighted edge appears on two faces; a corner appears on three. Centers fix the frame: white U, yellow D, green F. Camera rotation does not change it.</p>
      </section>
      <section className="encoding-arrays"><h3>2 · The same cube, stored as arrays</h3><p><b>Column = current slot. Number = piece identity.</b> IDs start at zero separately for edges and corners.</p>
        {Object.entries(names).map(([group,positions])=><div className="encoding-orbit" key={group}><h4>{group} <small>{positions.length} {group==='EDGES'?'two-sticker edges':'three-sticker corners'}</small></h4><div className="encoding-table-scroll"><table><thead><tr><th>index / slot</th>{positions.map((slot,i)=><th key={slot}><span>{i}</span><br/>{slot}</th>)}</tr></thead><tbody><tr><th>pieces</th>{state[group].pieces.map((value,i)=><td key={i}><button aria-label={`${group} slot ${positions[i]} contains piece ${value} ${positions[value]}`} aria-pressed={selected===positions[i]} onClick={()=>setSelected(positions[i])}><b>{value}</b><small>{positions[value]}</small><Dots home={positions[value]}/></button></td>)}</tr><tr><th>orientation</th>{state[group].orientation.map((value,i)=><td key={i}><button aria-label={`${group} ${positions[i]} orientation ${value}`} aria-pressed={selected===positions[i]} onClick={()=>setSelected(positions[i])}>{value}</button></td>)}</tr></tbody></table></div></div>)}
        <details><summary>Why numbers? What happened to centers?</summary><p>We keep cubing.js’s native representation so the mechanics library can apply permutations and orientation changes directly. Each number is an index into a fixed piece-name list. Names would carry the same identity, but changing the representation would require translation at the library boundary. These IDs are not scores, colors or recommended moves.</p><p>Centers stay in the same positions during this experiment’s face turns. Their fixed colors label the six directions. The raw mechanics record also contains centers, but they are not another set of movable targets here.</p></details>
      </section>
    </div>
    <div className="encoding-decode"><h3>↓ 3 · Decode the selected entry</h3><div className="encoding-equation"><code>{orbit}.pieces[<mark>{index}</mark>] = <mark>{id}</mark></code><span>→</span><p>At <b>{selected}</b> ({[...selected].map(f=>faceNames[f].toLowerCase()).join(' / ')}), find piece <b>{slots[id]}</b> <Dots home={slots[id]}/></p></div>
      <div className="encoding-decoded-grid"><div><h4>Index {index}: where it is now</h4><p>The {orbit.toLowerCase()} slot list maps index {index} to <b>{selected}</b>. This position stays fixed while pieces move through it.</p></div><div><h4>Value {id}: which piece it is</h4><p>The same list maps ID {id} to <b>{piece.piece}</b>, its home slot. Its stickers are {[...piece.piece].map(f=>colors[f]).join(' + ')}. The identity stays with the piece as it moves.</p></div><div><h4>Orientation {orientation}: which way it faces</h4><p>{piece.kind==='edge'?'Edges have two possible orientations, 0 or 1.':'Corners have three possible orientations, 0, 1 or 2.'} These are library conventions relative to the ordered slot labels. Zero alone does not mean solved.</p><div className="encoding-sticker-map">{Object.entries(piece.stickers).map(([color,direction])=><span key={color}><i style={{background:palette[color]}}/>{color} → <b>{direction}</b></span>)}</div></div></div>
      <details><summary>Exact orientation decoding for this entry</summary><p>For sticker index j in the home label, its direction is currentSlot[(j − orientation + stickerCount) % stickerCount].</p>{[...piece.piece].map((face,j)=><p key={face}><code>{colors[face]}: {selected}[({j} − {orientation} + {piece.piece.length}) % {piece.piece.length}] = {piece.stickers[colors[face]]}</code></p>)}</details>
    </div>
    <div className="encoding-facts"><h3>↓ 4 · Measure facts for the first JEV request</h3><p>Code decodes every piece, then counts or checks current structures. These three examples show how measurements are built. The complete set is listed in request 1 below; JEV receives named facts rather than the numeric piece arrays.</p><div className="encoding-fact-grid"><div><code>completed.daisy = {observation.completed?.daisy}</code><p>Count edges whose yellow sticker points U.</p><div>{petals.length?petals.map(p=><button key={p.position} onClick={()=>{setSelected(p.position);setFlat(true);}}>{p.piece} at {p.position} · yellow ↑</button>):<span>No yellow-up edges.</span>}</div></div><div><code>uncollectedYellowEdges = {observation.uncollectedYellowEdges}</code><p>Yellow edges that are neither yellow-up petals nor solved bottom edges.</p><div>{uncollected.length?uncollected.map(p=><button key={p.position} onClick={()=>{setSelected(p.position);setFlat(true);}}>{p.piece} at {p.position}</button>):<span>None remaining.</span>}</div></div><div><code>completed.cross = {String(observation.completed?.cross)}</code><p>All four bottom edge slots must contain their home pieces with orientation 0. Click a bottom slot to inspect it.</p><div>{['DF','DR','DB','DL'].map(slot=><button key={slot} className={decoded.find(p=>p.position===slot)?.solved?'is-complete':''} onClick={()=>{setSelected(slot);setFlat(true);}}>{slot} {decoded.find(p=>p.position===slot)?.solved?'✓':'○'}</button>)}</div></div></div><p className="encoding-next">↓ These measurements join recent-action memory and fixed teaching in <a href="#wire-request-0">request 1: choose a goal</a>. JEV makes the choice.</p></div>
  </section>;
}
