import {readFileSync,writeFileSync} from 'node:fs';
import {apply,facts} from '../../src/lib/cube';
import {actions} from './policy';
const dir='experiments/less-help-v1';
const result=JSON.parse(readFileSync(`${dir}/results.json`,'utf8')),fixtures=JSON.parse(readFileSync(`${dir}/fixtures.json`,'utf8'));
const rows=result.rows;
const stateKeys=(split:string)=>new Set(rows.filter((r:any)=>r.split===split).map((r:any)=>JSON.stringify(r.exchanges[0]?.request.state)));
const dev=stateKeys('development'),val=stateKeys('validation');
const table=[];
for(const split of ['development','validation'])for(const variant of ['explicit','relational','minimal']){
 const rs=rows.filter((r:any)=>r.split===split&&r.variant===variant);if(!rs.length)continue;
 const exchanges=rs.flatMap((r:any)=>r.exchanges);let preserved=0;
 for(const r of rs)if(r.action!==undefined){const c=fixtures.find((c:any)=>c.id===r.id);if(facts(await apply(c.state,actions[r.action])).firstLayer)preserved++;}
 const times=exchanges.map((e:any)=>e.elapsedMs).sort((a:number,b:number)=>a-b);
 table.push({split,variant,total:rs.length,intention:rs.filter((r:any)=>r.intentCorrect).length,action:rs.filter((r:any)=>r.actionCorrect).length,complete:rs.filter((r:any)=>r.correct).length,bottomPreserved:preserved,requests:exchanges.length,tokens:exchanges.reduce((n:number,e:any)=>n+e.response.usage.input_tokens,0),cost:exchanges.reduce((n:number,e:any)=>n+e.cost,0),medianMs:times[Math.floor(times.length/2)],byFamily:Object.fromEntries(['done','flipped','trapped','align','insert'].map(f=>[f,rs.filter((r:any)=>r.family===f&&r.correct).length]))});
}
const summary={table,uniqueInputs:{development:dev.size,validation:val.size,overlap:[...val].filter(k=>dev.has(k)).length},usage:result.usage,budget:result.budget};
writeFileSync(`${dir}/summary.json`,JSON.stringify(summary,null,2));
writeFileSync(`${dir}/RESULTS.md`, `# Less-help middle-edge screening\n\n| Split | Teaching | Intention | Action | Both | Input tokens | Cost | Median call ms |\n|---|---|---:|---:|---:|---:|---:|---:|\n${table.map(r=>`| ${r.split} | ${r.variant} | ${r.intention}/20 | ${r.action}/20 | ${r.complete}/20 | ${r.tokens} | $${r.cost.toFixed(6)} | ${r.medianMs.toFixed(0)} |`).join('\n')}\n\n200 live calls, no retries or provider errors. Total $${result.usage.cost.toFixed(8)}. All actions preserve the bottom layer because the menu consists of routines that do so; preservation alone is not evidence of correct selection. No full solves were attempted.\n\n## Interpretation\n\nReduced-help variants recognize many trapped/flipped middle edges, but fail upper-edge alignment/insertion and often disturb already solved targets. The matched explicit baseline also fails, so this study does not isolate the cost of removing rules from the proven pipeline. It also removes computed solved/layer/alignment fields and combines reference and action choice, unlike production. In development-1, the blue-red edge is at UR, blue faces R and red faces U. The explicit arm chooses extract and middle-right@R; the acceptable immediate action is U-prime alignment. Calling the target a middle edge may be confused with current location. This is a hypothesis, not a demonstrated cause.\n\n## Limits and next experiment\n\nForty cube states are distinct, but the compact target-only observation collapses them to ${dev.size} development and ${val.size} validation inputs, with ${summary.uniqueInputs.overlap} overlapping between splits. Treat this as screening, not independent held-out evidence. Fix future fixture uniqueness at the actual request boundary, balance reference directions, and use contrasting current locations. Keep reliable location words (upper/front/right) in observations while avoiding tactical verdicts. Compare relational teaching to explicit rules with otherwise matched inputs; first test current-location recognition separately, then action choice. The minimal arm won development among reduced-help variants and was selected without tuning; both validation candidates remain inadequate. No production policy was changed.\n\nExact requests, responses, timings and accepted-answer sets: [results.json](results.json). Frozen builders, fixtures and protocol are in this directory. Scoring simulations run offline only.\n`);
console.log(JSON.stringify(summary));
